"""add_user_goals

Revision ID: 1c0830a92cf3
Revises: 0d66cc9e1b1a
Create Date: 2026-04-03 15:03:36.159232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0830a92cf3'
down_revision: Union[str, Sequence[str], None] = '0d66cc9e1b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goal_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('goal_deadline', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('goal_deadline')
        batch_op.drop_column('goal_type')
        batch_op.drop_column('target_weight')
        batch_op.drop_column('height')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
