"""add_photo_path_and_raw_response

Revision ID: 9d6eaddaaf91
Revises: 1c0830a92cf3
Create Date: 2026-04-03 15:06:41.083541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6eaddaaf91'
down_revision: Union[str, Sequence[str], None] = '1c0830a92cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ai_raw_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_column('ai_raw_response')
        batch_op.drop_column('photo_path')

    # ### end Alembic commands ###
